spring.application.name=connectx-backend

spring.datasource.url=jdbc:postgresql://db.ufepnyjhmwmkiozycezy.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=L9yeneEdQtM6pEIa
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

# WhatsApp / Meta
meta.app-id=${META_APP_ID:937194355652639}
meta.app-secret=${META_APP_SECRET:65f2da554a5b0dae0195bf79397afe27}
meta.graph-api-version=${META_GRAPH_API_VERSION:v26.0}
meta.system-user-access-token=${META_SYSTEM_USER_ACCESS_TOKEN:61594754904641}
whatsapp.verify-token=${WHATSAPP_VERIFY_TOKEN:connectx-dev-token}
whatsapp.access-token=${WHATSAPP_ACCESS_TOKEN:EAANUX5CneB8BSkHY12ckNpN1IpEgumPrcyzlY6tnVIEzi6Rq84QhelZA0k5Ium1rZBrWxqVPai6ZBa8vgG7uLyiPwCM0kZBMUcnCfVE78fdxLVBoHz3ZBdKKoB5bQZCiINlZBhghYqEilW8wj2Do82pe5nuSUbBgkUW0vIVORK7Akemi5RKl7O0E3cZAy94O1vGDwLbTc29xYjzZCnaZChluGqzmoo4k1bITUF0UHMtyFbD6TIVOKRwCN2919nzB3YesdI9iBdrXPohhOlvoXDUqoyffXvHgZDZD}
whatsapp.phone-number-id=${WHATSAPP_PHONE_NUMBER_ID:1287524524448452}
whatsapp.business-account-id=${WHATSAPP_BUSINESS_ACCOUNT_ID:29020601567626592}
whatsapp.app-secret=${WHATSAPP_APP_SECRET:65f2da554a5b0dae0195bf79397afe27}

# Google / Gmail
google.client-id=${GOOGLE_CLIENT_ID:900191005045-qha3ejq67maqqgv555bfpkr6u9l35tso.apps.googleusercontent.com}
google.client-secret=${GOOGLE_CLIENT_SECRET:your-google-client-secret}
google.redirect-uri=${GOOGLE_REDIRECT_URI:https://connectx-frontend-ruby.vercel.app/connect/gmail}